<?php /**@var \Shirish\TestModuleTwo\Block\Layout\Index $block */ ?>

<h2><?= $block->getSubtitle() ?></h2>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, repellendus? Laudantium hic, veniam repellendus
    nam fugit et nulla porro quidem optio iste iure explicabo perspiciatis aperiam dolores quas quibusdam molestiae
    vitae aspernatur eveniet placeat. Iusto iure explicabo corrupti obcaecati nam.</p>