<?php /** @var \Shirish\DependencyInjectionModule\Block\Example $block */ ?>
<div>
    <h2>Dependency Subtitle</h2>
</div>

<p>
    Class Main id is : (Static) <?= $block->getMain()->getId()?>
</p>

<p>
    Class Injectable id is : <?= $block->getMain()->getInjectable()->getId()?>
</p>

<p>
    Class NonInjectable id is : <?= $block->getMain()->getNonInjectable()->getId()?>
</p>


<p>
    Class AbstractUtil : : Util Name is : <?= $block->getMain()->getAbstractUtil()->getName()?>
</p>

<p>
    Class AbstractUtil : : Util Name is : <?= $block->getMain()->getHeavyOperation()->getName()?>
</p>