<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** */
?>
<?php $_product = $block->getProduct();
$_product = $block->getProduct();
dump($block->isSalableQuantity());

if ($block->isSalableQuantity()) {
    $buttonTitle = __('Add to Cart');
    $buttonUrl = 'javascript:void(0);';
} else {
    $buttonTitle = __('Call For Availability');
    $buttonUrl = 'http://shirishjaiswal.com/contact/';
}

?>
<?php if ($_product->isSaleable()) : ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) : ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number" name="qty" id="qty" min="0" value="<?= $block->getProductDefaultQty() * 1 ?>"
                    title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty"
                    data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart"
                id="product-addtocart-button" disabled
                <?= $block->isSalableQuantity() == false ? 'onclick="window.location.href=' . "'" . $buttonUrl . "'" . '"' : ''; ?>>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>